#!/bin/bash

# compilation/run settings
SRC=ots.cpp
OUT=ots
CC=mpic++
RUNNER=mpirun
FLAGS="--prefix /usr/local/share/OpenMPI"

# testing settings
GEN_FILE=numbers

function printHelp()
{
	echo "Usage: $0 <N>"
	echo ""
	echo "where:"
	echo "  N - total random numbers to be generated (must be greater > 0)."
}

function checkArgs()
{
	allargs="'$@'"
	[ "$allargs" == "''" ] && echo "error: expected argument" && printHelp && exit 1
	[ "'$1'" != "$allargs" ] && echo "error: expected just one argument" && printHelp && exit 1
	only_nums="$(echo "$1" | grep '^[0-9][0-9]*$')"
	[ -z "$only_nums" ] && echo "error: invalid N: " $1 && printHelp && exit 1
}

function main()
{
	checkArgs $@
	count=$1

	[ $count -eq 0 ] && return

	# create test file
	#dd if=/dev/random bs=1 count=$count of=$GEN_FILE &>/dev/null

	# compilation
	$CC $SRC $FLAGS -o $OUT

	# run
	$RUNNER $FLAGS -np $count $OUT

	# clean
	rm -f $OUT $GEN_FILE
}

main $@
exit 0
